#!/bin/bash

KB_TO_GB=$((1 << 20))

if [ -z "$1" ]; then
  echo "Usage: $0 <application_name>"
  exit 1
fi

APP_NAME="$1"

TOTAL_PROCESSES=$(ps aux | grep "$APP_NAME" | grep -v grep | wc -l)
TOTAL_MEMORY_KB=$(ps aux | grep "$APP_NAME" | grep -v grep | awk '{x+=$6} END {print x}')
TOTAL_MEMORY_GB=$(echo "scale=2; $TOTAL_MEMORY_KB / $KB_TO_GB" | bc)

echo "Total processes: $TOTAL_PROCESSES"
echo "Total memory usage: $TOTAL_MEMORY_GB GB"
